/**
 * Every country the platform can name (UN member and observer states, Kosovo, Hong Kong and Taiwan), with its
 * continent. Used for the partner programme: one page and one partner fee per country, and the "where are you"
 * pickers on the legal pages. Pure data, shared by server and browser.
 */
export type Continent = 'africa' | 'europe' | 'asia' | 'north-america' | 'south-america' | 'oceania'

export interface WorldCountry {
    /** ISO 3166-1 alpha-2 (XK is the user-assigned code commonly used for Kosovo). */
    code: string
    name: string
    continent: Continent
}

const row = (code: string, name: string, continent: Continent): WorldCountry => ({ code, name, continent })

export const WORLD_COUNTRIES: WorldCountry[] = [
    row('DZ', 'Algeria', 'africa'),
    row('AO', 'Angola', 'africa'),
    row('BJ', 'Benin', 'africa'),
    row('BW', 'Botswana', 'africa'),
    row('BF', 'Burkina Faso', 'africa'),
    row('BI', 'Burundi', 'africa'),
    row('CV', 'Cabo Verde', 'africa'),
    row('CM', 'Cameroon', 'africa'),
    row('CF', 'Central African Republic', 'africa'),
    row('TD', 'Chad', 'africa'),
    row('KM', 'Comoros', 'africa'),
    row('CG', 'Congo', 'africa'),
    row('CD', 'DR Congo', 'africa'),
    row('CI', "Côte d'Ivoire", 'africa'),
    row('DJ', 'Djibouti', 'africa'),
    row('EG', 'Egypt', 'africa'),
    row('GQ', 'Equatorial Guinea', 'africa'),
    row('ER', 'Eritrea', 'africa'),
    row('SZ', 'Eswatini', 'africa'),
    row('ET', 'Ethiopia', 'africa'),
    row('GA', 'Gabon', 'africa'),
    row('GM', 'Gambia', 'africa'),
    row('GH', 'Ghana', 'africa'),
    row('GN', 'Guinea', 'africa'),
    row('GW', 'Guinea-Bissau', 'africa'),
    row('KE', 'Kenya', 'africa'),
    row('LS', 'Lesotho', 'africa'),
    row('LR', 'Liberia', 'africa'),
    row('LY', 'Libya', 'africa'),
    row('MG', 'Madagascar', 'africa'),
    row('MW', 'Malawi', 'africa'),
    row('ML', 'Mali', 'africa'),
    row('MR', 'Mauritania', 'africa'),
    row('MU', 'Mauritius', 'africa'),
    row('MA', 'Morocco', 'africa'),
    row('MZ', 'Mozambique', 'africa'),
    row('NA', 'Namibia', 'africa'),
    row('NE', 'Niger', 'africa'),
    row('NG', 'Nigeria', 'africa'),
    row('RW', 'Rwanda', 'africa'),
    row('ST', 'São Tomé and Príncipe', 'africa'),
    row('SN', 'Senegal', 'africa'),
    row('SC', 'Seychelles', 'africa'),
    row('SL', 'Sierra Leone', 'africa'),
    row('SO', 'Somalia', 'africa'),
    row('ZA', 'South Africa', 'africa'),
    row('SS', 'South Sudan', 'africa'),
    row('SD', 'Sudan', 'africa'),
    row('TZ', 'Tanzania', 'africa'),
    row('TG', 'Togo', 'africa'),
    row('TN', 'Tunisia', 'africa'),
    row('UG', 'Uganda', 'africa'),
    row('ZM', 'Zambia', 'africa'),
    row('ZW', 'Zimbabwe', 'africa'),
    row('AL', 'Albania', 'europe'),
    row('AD', 'Andorra', 'europe'),
    row('AT', 'Austria', 'europe'),
    row('BY', 'Belarus', 'europe'),
    row('BE', 'Belgium', 'europe'),
    row('BA', 'Bosnia and Herzegovina', 'europe'),
    row('BG', 'Bulgaria', 'europe'),
    row('HR', 'Croatia', 'europe'),
    row('CY', 'Cyprus', 'europe'),
    row('CZ', 'Czechia', 'europe'),
    row('DK', 'Denmark', 'europe'),
    row('EE', 'Estonia', 'europe'),
    row('FI', 'Finland', 'europe'),
    row('FR', 'France', 'europe'),
    row('DE', 'Germany', 'europe'),
    row('GR', 'Greece', 'europe'),
    row('HU', 'Hungary', 'europe'),
    row('IS', 'Iceland', 'europe'),
    row('IE', 'Ireland', 'europe'),
    row('IT', 'Italy', 'europe'),
    row('XK', 'Kosovo', 'europe'),
    row('LV', 'Latvia', 'europe'),
    row('LI', 'Liechtenstein', 'europe'),
    row('LT', 'Lithuania', 'europe'),
    row('LU', 'Luxembourg', 'europe'),
    row('MT', 'Malta', 'europe'),
    row('MD', 'Moldova', 'europe'),
    row('MC', 'Monaco', 'europe'),
    row('ME', 'Montenegro', 'europe'),
    row('NL', 'Netherlands', 'europe'),
    row('MK', 'North Macedonia', 'europe'),
    row('NO', 'Norway', 'europe'),
    row('PL', 'Poland', 'europe'),
    row('PT', 'Portugal', 'europe'),
    row('RO', 'Romania', 'europe'),
    row('RU', 'Russia', 'europe'),
    row('SM', 'San Marino', 'europe'),
    row('RS', 'Serbia', 'europe'),
    row('SK', 'Slovakia', 'europe'),
    row('SI', 'Slovenia', 'europe'),
    row('ES', 'Spain', 'europe'),
    row('SE', 'Sweden', 'europe'),
    row('CH', 'Switzerland', 'europe'),
    row('UA', 'Ukraine', 'europe'),
    row('GB', 'United Kingdom', 'europe'),
    row('VA', 'Vatican City', 'europe'),
    row('AF', 'Afghanistan', 'asia'),
    row('AM', 'Armenia', 'asia'),
    row('AZ', 'Azerbaijan', 'asia'),
    row('BH', 'Bahrain', 'asia'),
    row('BD', 'Bangladesh', 'asia'),
    row('BT', 'Bhutan', 'asia'),
    row('BN', 'Brunei', 'asia'),
    row('KH', 'Cambodia', 'asia'),
    row('CN', 'China', 'asia'),
    row('GE', 'Georgia', 'asia'),
    row('IN', 'India', 'asia'),
    row('ID', 'Indonesia', 'asia'),
    row('IR', 'Iran', 'asia'),
    row('IQ', 'Iraq', 'asia'),
    row('IL', 'Israel', 'asia'),
    row('JP', 'Japan', 'asia'),
    row('JO', 'Jordan', 'asia'),
    row('KZ', 'Kazakhstan', 'asia'),
    row('KW', 'Kuwait', 'asia'),
    row('KG', 'Kyrgyzstan', 'asia'),
    row('LA', 'Laos', 'asia'),
    row('LB', 'Lebanon', 'asia'),
    row('MY', 'Malaysia', 'asia'),
    row('MV', 'Maldives', 'asia'),
    row('MN', 'Mongolia', 'asia'),
    row('MM', 'Myanmar', 'asia'),
    row('NP', 'Nepal', 'asia'),
    row('KP', 'North Korea', 'asia'),
    row('OM', 'Oman', 'asia'),
    row('PK', 'Pakistan', 'asia'),
    row('PS', 'Palestine', 'asia'),
    row('PH', 'Philippines', 'asia'),
    row('QA', 'Qatar', 'asia'),
    row('SA', 'Saudi Arabia', 'asia'),
    row('SG', 'Singapore', 'asia'),
    row('KR', 'South Korea', 'asia'),
    row('LK', 'Sri Lanka', 'asia'),
    row('SY', 'Syria', 'asia'),
    row('TJ', 'Tajikistan', 'asia'),
    row('TH', 'Thailand', 'asia'),
    row('TL', 'Timor-Leste', 'asia'),
    row('TR', 'Türkiye', 'asia'),
    row('TM', 'Turkmenistan', 'asia'),
    row('AE', 'United Arab Emirates', 'asia'),
    row('UZ', 'Uzbekistan', 'asia'),
    row('VN', 'Vietnam', 'asia'),
    row('YE', 'Yemen', 'asia'),
    row('HK', 'Hong Kong', 'asia'),
    row('TW', 'Taiwan', 'asia'),
    row('US', 'United States', 'north-america'),
    row('CA', 'Canada', 'north-america'),
    row('MX', 'Mexico', 'north-america'),
    row('GT', 'Guatemala', 'north-america'),
    row('BZ', 'Belize', 'north-america'),
    row('SV', 'El Salvador', 'north-america'),
    row('HN', 'Honduras', 'north-america'),
    row('NI', 'Nicaragua', 'north-america'),
    row('CR', 'Costa Rica', 'north-america'),
    row('PA', 'Panama', 'north-america'),
    row('CU', 'Cuba', 'north-america'),
    row('DO', 'Dominican Republic', 'north-america'),
    row('HT', 'Haiti', 'north-america'),
    row('JM', 'Jamaica', 'north-america'),
    row('BS', 'Bahamas', 'north-america'),
    row('BB', 'Barbados', 'north-america'),
    row('TT', 'Trinidad and Tobago', 'north-america'),
    row('AG', 'Antigua and Barbuda', 'north-america'),
    row('DM', 'Dominica', 'north-america'),
    row('GD', 'Grenada', 'north-america'),
    row('KN', 'Saint Kitts and Nevis', 'north-america'),
    row('LC', 'Saint Lucia', 'north-america'),
    row('VC', 'Saint Vincent and the Grenadines', 'north-america'),
    row('AR', 'Argentina', 'south-america'),
    row('BO', 'Bolivia', 'south-america'),
    row('BR', 'Brazil', 'south-america'),
    row('CL', 'Chile', 'south-america'),
    row('CO', 'Colombia', 'south-america'),
    row('EC', 'Ecuador', 'south-america'),
    row('GY', 'Guyana', 'south-america'),
    row('PY', 'Paraguay', 'south-america'),
    row('PE', 'Peru', 'south-america'),
    row('SR', 'Suriname', 'south-america'),
    row('UY', 'Uruguay', 'south-america'),
    row('VE', 'Venezuela', 'south-america'),
    row('AU', 'Australia', 'oceania'),
    row('NZ', 'New Zealand', 'oceania'),
    row('FJ', 'Fiji', 'oceania'),
    row('PG', 'Papua New Guinea', 'oceania'),
    row('WS', 'Samoa', 'oceania'),
    row('TO', 'Tonga', 'oceania'),
    row('VU', 'Vanuatu', 'oceania'),
    row('SB', 'Solomon Islands', 'oceania'),
    row('KI', 'Kiribati', 'oceania'),
    row('FM', 'Micronesia', 'oceania'),
    row('MH', 'Marshall Islands', 'oceania'),
    row('PW', 'Palau', 'oceania'),
    row('NR', 'Nauru', 'oceania'),
    row('TV', 'Tuvalu', 'oceania'),
].sort((a, b) => a.name.localeCompare(b.name))

const BY_CODE = new Map(WORLD_COUNTRIES.map((c) => [c.code, c]))

export const worldCountry = (code: string | undefined | null): WorldCountry | undefined => (code ? BY_CODE.get(code.toUpperCase()) : undefined)

export const slugOf = (name: string): string =>
    name
        .normalize('NFD')
        .replace(/[\u0300-\u036f]/g, '')
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, '-')
        .replace(/^-|-$/g, '')

/** The country whose slug (for example "united-kingdom") or code (for example "GB") this is. */
export function worldCountryByParam(param: string | undefined | null): WorldCountry | undefined {
    if (!param) return undefined
    const p = param.toLowerCase()
    return WORLD_COUNTRIES.find((c) => slugOf(c.name) === p || c.code.toLowerCase() === p)
}
